<?php

/**
 * Copyright (C) 2008-2012 FluxBB
 * based on code by Rickard Andersson copyright (C) 2002-2008 PunBB
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher
 *
 * PDO-based implementation of the DBLayer interface. Dialect specifics
 * (schema helpers, version strings, transaction semantics) live in the
 * per-database subclasses: MysqlPdoDBLayer, SqlitePdoDBLayer,
 * PgsqlPdoDBLayer.
 */

if (!class_exists('PDO'))
	exit('This PHP environment doesn\'t have PDO support built in. PDO support is required if you want to use a PDO database driver to run this forum. Consult the PHP documentation for further assistance.');

require_once PUN_ROOT.'include/dblayer/interface.php';


/**
 * Result-set wrapper. The legacy drivers hand out resources/objects that
 * support random access (data_seek); PDO statements are forward-only, so
 * buffered queries are materialized up front while unbuffered ones
 * stream from the live statement.
 */
class PdoDBResult
{
	public $rows = null;		// array of FETCH_BOTH rows when buffered
	public $cursor = 0;
	public $statement = null;	// live PDOStatement when unbuffered

	public function __construct($statement, $unbuffered)
	{
		if ($unbuffered)
			$this->statement = $statement;
		else
		{
			$this->rows = $statement->fetchAll(PDO::FETCH_BOTH);
			$statement->closeCursor();
		}
	}

	public function fetch($mode)
	{
		if ($this->statement !== null)
		{
			$row = $this->statement->fetch($mode);
			return ($row === false || $row === null) ? false : $row;
		}

		if (!isset($this->rows[$this->cursor]))
			return false;

		$row = $this->rows[$this->cursor++];

		if ($mode == PDO::FETCH_ASSOC)
			return array_filter($row, 'is_string', ARRAY_FILTER_USE_KEY);
		else if ($mode == PDO::FETCH_NUM)
			return array_values(array_filter($row, 'is_int', ARRAY_FILTER_USE_KEY));

		return $row;
	}

	public function result($row, $col)
	{
		if ($this->statement !== null)
		{
			// Forward-only: skip ahead to the requested row
			for ($i = 0; $i < $row; $i++)
				if ($this->statement->fetch(PDO::FETCH_NUM) === false)
					return false;

			$cur_row = $this->statement->fetch(PDO::FETCH_NUM);
			return ($cur_row !== false && $cur_row !== null && isset($cur_row[$col])) ? $cur_row[$col] : false;
		}

		if (!isset($this->rows[$row]))
			return false;

		$values = array_values(array_filter($this->rows[$row], 'is_int', ARRAY_FILTER_USE_KEY));
		return isset($values[$col]) ? $values[$col] : false;
	}

	public function num_rows()
	{
		if ($this->rows !== null)
			return count($this->rows);

		// Row count of an unbuffered result is unknowable without
		// consuming it; rowCount() is the best PDO offers
		return $this->statement->rowCount();
	}

	public function free()
	{
		if ($this->statement !== null)
			$this->statement->closeCursor();
		$this->rows = null;
		$this->statement = null;
	}
}


abstract class PdoDBLayer implements DBLayer
{
	var $prefix;
	var $pdo;
	var $query_result;

	var $saved_queries = array();
	var $num_queries = 0;
	var $in_transaction = 0;

	var $error_no = false;
	var $error_msg = 'Unknown';

	var $datatype_transformations = array();

	var $last_insert_id = 0;
	var $last_affected_rows = 0;
	var $last_query_text = '';

	/**
	 * Subclasses connect and assign $this->pdo, then call init_connection().
	 */
	protected function init_connection()
	{
		// Exception mode, caught centrally in query(): pdo_pgsql on
		// PHP 8.4 misreports successful DDL as false in silent mode,
		// so return-value emulation is done via try/catch instead
		$this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	}


	function start_transaction()
	{
		return;
	}


	function end_transaction()
	{
		return;
	}


	function query($sql, $unbuffered = false)
	{
		if (defined('PUN_SHOW_QUERIES'))
			$q_start = microtime(true);

		try
		{
			$statement = $this->pdo->query($sql);
		}
		catch (PDOException $e)
		{
			if (defined('PUN_SHOW_QUERIES'))
				$this->saved_queries[] = array($sql, 0);

			$error = $e->errorInfo;
			$this->error_no = isset($error[1]) ? $error[1] : false;
			$this->error_msg = isset($error[2]) ? $error[2] : $e->getMessage();

			if ($this->in_transaction)
			{
				try { $this->pdo->exec('ROLLBACK'); } catch (PDOException $ignored) {}
				--$this->in_transaction;
			}

			return false;
		}

		if (defined('PUN_SHOW_QUERIES'))
			$this->saved_queries[] = array($sql, sprintf('%.5F', microtime(true) - $q_start));

		++$this->num_queries;

		$this->last_query_text = $sql;
		$this->last_affected_rows = $statement->rowCount();

		$this->query_result = new PdoDBResult($statement, $unbuffered);

		return $this->query_result;
	}


	/**
	 * Dialect hook: how to read the id generated by the most recent
	 * INSERT/REPLACE. Called lazily from insert_id().
	 */
	protected function fetch_insert_id()
	{
		try
		{
			return (int) $this->pdo->lastInsertId();
		}
		catch (PDOException $e)
		{
			return 0;
		}
	}


	function result($query_id = 0, $row = 0, $col = 0)
	{
		return ($query_id instanceof PdoDBResult) ? $query_id->result($row, $col) : false;
	}


	function fetch_assoc($query_id = 0)
	{
		return ($query_id instanceof PdoDBResult) ? $query_id->fetch(PDO::FETCH_ASSOC) : false;
	}


	function fetch_row($query_id = 0)
	{
		return ($query_id instanceof PdoDBResult) ? $query_id->fetch(PDO::FETCH_NUM) : false;
	}


	function has_rows($query_id)
	{
		return ($query_id instanceof PdoDBResult) ? $query_id->num_rows() > 0 : false;
	}


	function affected_rows()
	{
		return ($this->pdo) ? $this->last_affected_rows : false;
	}


	function insert_id()
	{
		return ($this->pdo) ? $this->fetch_insert_id() : false;
	}


	function get_num_queries()
	{
		return $this->num_queries;
	}


	function get_saved_queries()
	{
		return $this->saved_queries;
	}


	function free_result($query_id = false)
	{
		if ($query_id instanceof PdoDBResult)
		{
			$query_id->free();
			return true;
		}

		return false;
	}


	function escape($str)
	{
		if (is_array($str))
			return '';

		// PDO::quote() returns the string with surrounding quotes; the
		// codebase adds its own quotes, so strip them
		$quoted = $this->pdo->quote((string) $str);
		return substr($quoted, 1, -1);
	}


	function error()
	{
		$last_query = end($this->saved_queries);

		$result['error_sql'] = is_array($last_query) ? current($last_query) : '';
		$result['error_no'] = $this->error_no;
		$result['error_msg'] = $this->error_msg;

		return $result;
	}


	function close()
	{
		if ($this->pdo)
		{
			if ($this->in_transaction)
			{
				if (defined('PUN_SHOW_QUERIES'))
					$this->saved_queries[] = array('COMMIT', 0);

				try { $this->pdo->exec('COMMIT'); } catch (PDOException $ignored) {}
				$this->in_transaction = 0;
			}

			$this->query_result = null;
			$this->pdo = null;

			return true;
		}
		else
			return false;
	}
}
